### PR TITLE
Add ClassNotFoundException

### PR DESCRIPTION
**Pull request by summer-alice**
This adds the `ClassNotFoundException` class.

As sort of mentioned in #103, when trying to implement a new constructor for the `Image` class, I encountered a cyclic dependency error.

I have a local fix complete, this is just the beginning of it.

This also drops support for Tango in the file.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
It sounds like `ClassNotFoundException` might be thrown when a class is dynamically loaded in Java. Is that applicable on D? How will this exception be used in D?

**Comment by summer-alice** [comment]
> It sounds like `ClassNotFoundException` might be thrown when a class is dynamically loaded in Java. Is that applicable on D?

Yea that's about it. In D, the same is achieved with `Object.factory`, however, the return form that is null if the class can't be found (instead of the exception).

> How will this exception be used in D?

My intention for adding this was so it can be used by the implementation of `Class.forName`. This just allows the DWT code to consistent with SWT. (e.g. `FileFormat` (lines [33-38] & [70-87]).)

[33-38]: https://github.com/eclipse/eclipse.platform.swt/blob/R4_7_3/bundles/org.eclipse.swt/Eclipse%20SWT/common/org/eclipse/swt/internal/image/FileFormat.java#L33-L38

[70-87]: https://github.com/eclipse/eclipse.platform.swt/blob/R4_7_3/bundles/org.eclipse.swt/Eclipse%20SWT/common/org/eclipse/swt/internal/image/FileFormat.java#L70-L87

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by summer-alice** [comment]
> Thanks.

Thank you.

**Pull request merged**
