### PR TITLE
Update CTabItem to 4.7.3

### PR DESCRIPTION
**Pull request by summer-alice**
Moves the `CTabItem` class into the new "common" directory, and updates the code to match SWT version 4.7.3.

### CODE REVIEW

**Comment by summer-alice** [comment]
okay... not entirely sure why those snippets decided to fail *now*. I don't think it's something I've done, but will have a look.

**Comment by summer-alice** [comment]
A quick follow through of the imports and it seems that the `alias to!(string) toString` previously declared in CTabItem[[1]] was being publicly imported in `org.eclipse.swt.all`[[2]], which in turn was imported in the snippets[[3]].

I think it's probably better to change the snippets to use `to!string()`. Did you want me to change it in a separate pull request or just change it in this one?

[1]: https://github.com/d-widget-toolkit/dwt/blob/7581565/org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/custom/CTabItem.d#L39

[2]: https://github.com/d-widget-toolkit/dwt/blob/7581565/org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/all.d#L11

[3]: https://github.com/d-widget-toolkit/dwt/blob/7581565/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet6.d#L54

**Comment by jacob-carlborg** [comment]
> I think it's probably better to change the snippets to use to!string(). Did you want me to change it in a separate pull request or just change it in this one?

Apologies for the late reply.  Isn't it better to have a `toString` function? It would result in less changes compared to SWT. But I think it's your call, you're doing most of the work now.

**Comment by summer-alice** [comment]
> Apologies for the late reply.

No worries.

> Isn't it better to have a `toString` function? It would result in less changes compared to SWT. 

Yea that is true.

> But I think it's your call, you're doing most of the work now.

I'll move the alias to `base/src/java/lang/String.d` since, to me, that makes the most sense (the other D-to-Java string related functions are there).

**Comment by jacob-carlborg** [comment]
> I'll move the alias to base/src/java/lang/String.d since, to me, that makes the most sense (the other D-to-Java string related functions are there).

Sounds good.

**Comment by summer-alice** [comment]
Okay, the CI passes now. It took a while to complete because one of the VM's took a while to start up.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
🙇

**Comment by summer-alice** [comment]
Thank you.

**Pull request merged**
