### PR TITLE
Rollback to b54c611

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Comment by kntroh** [comment]
It worked fine!

**Comment by summer-alice** [comment]
Seems fine, it also works for me.

To make sure I understand correctly... once this is merged I can create a merge request the same as #91 for both the `master` and `4.7` branches? The other merge requests can also be re-sent but just target the `4.7` branch?

**Comment by jacob-carlborg** [comment]
> To make sure I understand correctly... once this is merged I can create a merge request the same as #91 for both the master and 4.7 branches?

If #91 should be in master I don't have to revert that one.

> The other merge requests can also be re-sent but just target the 4.7 branch?

**Comment by jacob-carlborg** [comment]
Now #91 is not reverted.

**Comment by summer-alice** [comment]
Yep looks all good.

**Pull request merged**
