### PR TITLE
Add AccessibleAttribute classes

### PR DESCRIPTION
**Pull request by summer-alice**
This translates the Java versions of the `AccessibleAttributeAdapter`, `AccessibleAttributeEvent`, and `AccessibleAttributeListener` classes to D.

The code is the same for both win32 and Gtk.

---
As an aside, have you given any thought to reorganizing the repository structure (ref #77)?  While it's no issue for me duplicating the code, you've previously said smaller diffs are better.

(not trying to rush you by asking this)

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
> As an aside, have you given any thought to reorganizing the repository structure (ref #77)? While it's no issue for me duplicating the code, you've previously said smaller diffs are better.

No, not really. I guess the most natural way would be to follow the same structure as the SWT git repository.

**Comment by summer-alice** [comment]
> Thanks.

Thank you.

**Comment by summer-alice** [comment]
> > As an aside, have you given any thought to reorganizing the repository structure (ref #77)? While it's no issue for me duplicating the code, you've previously said smaller diffs are better.
> 
> No, not really.

No worries :-)

> I guess the most natural way would be to follow the same structure as the SWT git repository.

I don't have any objections to that, the only issue I see with it is a large `dub.sdl` file -- if I'm correct in assuming this would require changes to the `sourcePaths` tag.

**Comment by jacob-carlborg** [comment]
> I see with it is a large dub.sdl file -- if I'm correct in assuming this would require changes to the sourcePaths tag.

Yes, it would require changes to `sourcePaths`. It would require to add 10-11 entries to `sourcePaths`. I don't think that's a big problem.

**Comment by summer-alice** [comment]
> It would require adding 10-11 entries to `sourcePaths`. I don't think that's a big problem.

I probably shouldn't have said "issue" since it's not really, rather it's just the only downside I could think of compared to a separate directory which contained the "common" stuff, since (in theory) this would only require one new entry for each configuration.

In the end there is no real difference, so when you've decided on a layout let us know :)

**Comment by jacob-carlborg** [comment]
> so when you've decided on a layout let us know :)

I apologize for the delay. Let's go with the same structure as the SWT repository.

**Comment by summer-alice** [comment]
> I apologize for the delay.

Same here.

> Let's go with the same structure as the SWT repository.

No worries, I'll create a draft pull request soon.

**Pull request merged**
