### PR TITLE
[Linux] Fix crash when LANG is empty, C, or POSIX

### PR DESCRIPTION
**Pull request by summer-alice**
So my [last attempt] didn't actually fix it. I thought I tested it, but apparently not... my bad.

I've changed the `caltureName` implementation for `version(Posix)` to use the [`setlocale`], which will check all applicable  environment variables for us.

I also changed `ResourceBundle.this(in ImportData[])` to check if the string has enough characters before attempting a splice.

You can check this works with the [a CI run from my `update-swt-4.7` branch][lci] (which had been [failing] because of this issue) after I'd pushed these changes.

[last attempt]: https://github.com/d-widget-toolkit/dwt/pull/115
[`setlocale`]: https://www.man7.org/linux/man-pages/man3/setlocale.3.html
[lci]: https://github.com/summer-alice/dwt/actions/runs/6036656687
[failing]: https://github.com/summer-alice/dwt/actions/runs/6035161590

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
I'm not following. The tests for the previous PR passed. Why did the test fail in your fork?

**Comment by summer-alice** [comment]
> I'm not following. The tests for the previous PR passed. Why did the test fail in your fork?

My fork adds a [new unittest][1] that [checks `SWT.getMessage`][2], which ends up calling `ResourceBundle.getBundle` (which itself uses `ResourceBundle.this(in ImportData[])`).

Since the previous pull request doesn't contain the unittest (nor does this one, hence the initial links), it couldn't be verified by the CI. I reckon I did the same thing when testing locally (not actually using the new unittest :grimacing:).

[1]: https://github.com/summer-alice/dwt/blob/update-swt-4.7/tests/SWT.d
[2]: https://github.com/summer-alice/dwt/blob/update-swt-4.7/tests/SWT.d#L80

**Comment by jacob-carlborg** [comment]
So perhaps we should add a test 😉.

**Comment by summer-alice** [comment]
Fair point :smile: 

I've added the SWT tests that I'd been talking about, as well as a specific test for invoking `caltureName` when `LC_ALL` and `LANG` are not set.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Pull request merged**
