### PR TITLE
Update which libraries the snippets link to on Linux

### PR DESCRIPTION
**Pull request by torhus**
gnomeui-2 and gnomevfs-2 are outdated and hard to find, replaced with gio-2.0.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Could you please update the readme as well.

**Comment by torhus** [comment]
By the way, is there any reason why the libs are not just listed in dub.sdl, like they are for the Windows build?

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
They are not the same on all Linux distributions.

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by torhus** [comment]
Not sure I see what you mean, I can create another pull request that does just this.

**Pull request merged**
