### PR TITLE
Start update of CTabFolder to 4.7.3

### PR DESCRIPTION
**Pull request by summer-alice**
This will start the process of updating CTabFolder to match what is in SWT 4.7.3.

`CTabFolderLayout` will also be updated to SWT 4.7.3 as there aren't too many changes.

### CODE REVIEW

**Comment by summer-alice** [comment]
So this doesn't compile, which I was aware of before creating the pull request.

The issue is that the Java version of `CTabFolderRenderer` has the method `computeSize` with the `protected` visibility. This doesn't translate one-to-one in D because of the difference between Java's packages and D's modules (in Java, multiple files can share the same package declaration, not so in D).

I was going to make the `computeSize` method have a visibility of `package(org.eclipse.swt.custom)`, but wanted to check if this was okay with you?

**Comment by jacob-carlborg** [comment]
> So this doesn't compile, which I was aware of before creating the pull request.
The issue is that the CTabFolderLayout class calls the computeSize method from an instance of the CTabFolderRenderer class. In SWT, the computeSize method has a visibility of protected

The CI pipeline is failing for a different reason.

> I was going to make the computeSize method have a visibility of package(org.eclipse.swt.custom), but wanted to check if this was okay with you?

Unfortunately in D, a method which has the `package` visibility will not be virtual. A method which is `protected` is intended to be overridden, that means it needs to be virtual. Unless it's possible to combine `package` and `protected` it needs to be `public`.

**Comment by summer-alice** [comment]
> > So this doesn't compile, which I was aware of before creating the pull request.
> > The issue is that the CTabFolderLayout class calls the computeSize method from an instance of the CTabFolderRenderer class. In SWT, the computeSize method has a visibility of protected
> 
> The CI pipeline is failing for a different reason.

Odd, on my machine it lists more errors -- two of which are about what I described. I'll try fix the errors not directly related to the issue I'm describing here.

The errors are:

    org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/custom/CTabFolderLayout.d(48,43): Error: no property computeSize for type org.eclipse.swt.custom.CTabFolderRenderer.CTabFolderRenderer
    org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/custom/CTabFolderLayout.d(52,29): Error: no property computeSize for type org.eclipse.swt.custom.CTabFolderRenderer.CTabFolderRenderer

> > I was going to make the computeSize method have a visibility of package(org.eclipse.swt.custom), but wanted to check if this was okay with you?
> 
> Unfortunately in D, a method which has the `package` visibility will not be virtual. A method which is `protected` is intended to be overridden, that means it needs to be virtual. Unless it's possible to combine `package` and `protected` it needs to be `public`.

It's not possible to combine the two (`Error: conflicting protection attribute package and protected`), so I'll make them public.

**Comment by summer-alice** [comment]
Okay, this pull request turned out larger than anticipated.

It doesn't fully port the CTabFolder class (some methods aren't deleted yet, some haven't been implemented). I'll do that in a follow up pull request (which will also add unittests).

**Comment by jacob-carlborg** [comment]
Is this good to merge as is or should I wait for the other PR?

**Comment by summer-alice** [comment]
> Is this good to merge as is or should I wait for the other PR?

The follow up merge request would build on this one (fill in the missing function bodies, remove outdated ones, etc.), so I'd prefer that this is merged first.

That said, I'm happy to make the changes in this merge request -- if you don't mind a somewhat larger diff.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by summer-alice** [comment]
> Thanks.

Thank you.

**Pull request merged**
