### PR TITLE
Changed int to long. GLib uses ctype long long

### PR DESCRIPTION
**Pull request by jaapgeurts**
Using int caused Text widget to crash when entering text.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Do you have any reference to the documentation for this?

**Comment by jaapgeurts** [comment]
Thanks for pushing me to investigate further. Glib does not indeed force any size. However what I think is happening here is this.
A pointer to a char is passed as an int to g_signal_emit_by_name1(). An int in D is 32bit but a pointer on a 64 bit system (my system) is 64bit. So information is lost and a crash happens in strlen (in libc).

see my stacktrace:
#0  0x00007ffff2877f01 in __strlen_avx2 () at /lib64/libc.so.6
#1  0x00007ffff697ec03 in g_strdup
    (str=0xd8015710 <error: Cannot access memory at address 0xd8015710>) at gstrfuncs.c:362
#2  0x00007ffff6c63f3c in value_collect_string
    (value=0x7fffffffb2d8, n_collect_values=<optimized out>, collect_values=<optimized out>, collect_flags=<optimized out>) at gvaluetypes.c:291
#3  0x00007ffff6c53ae9 in g_signal_emit_valist
    (instance=instance@entry=0xfe05b0, signal_id=signal_id@entry=165, detail=<optimized out>, var_args=var_args@entry=0x7fffffffb4d8) at gsignal.c:3369
#4  0x00007ffff6c55128 in g_signal_emit_by_name
    (instance=0xfe05b0, detailed_signal=0x9506e2 <_TMP14555> "commit") at gsignal.c:3487
#5  0x0000000000840cc1 in org.eclipse.swt.internal.gtk.OS.g_signal_emit_by_name1(void*, const(char*), int)
    (value=-671000816, detailed_signal=0x9506e2 <_TMP14555> "commit", instance=0xfe05b0)
    at ../../.dub/packages/dwt-1.0.1_swt-3.4.1/dwt/org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/gtk/OS.d:562
#6  0x00000000007b8c74 in _D3org7eclipse3swt8internal3gtk2OSQd10__mixin70122g_signal_emit_by_name1FPvxPaiZv
    (_param_2=-671000816, _param_1=0x9506e2 <_TMP14555> "commit", _param_0=0xfe05b0)
    at ../../.dub/packages/dwt-1.0.1_swt-3.4.1/dwt/org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/internal/gtk/OS.d-mixin-657:660
#7  0x00000000007377ff in _D3org7eclipse3swt7widgets4TextQf10gtk_commitMFPSQBvQBuQBp8internal1c3gtk13_GtkIMContextPaZi
--Type <RET> for more, q to quit, c to continue without paging--
    (this=0x7ffff7eb2200, text=0x7fffd8015710 "q", imcontext=0xfe05b0)
    at ../../.dub/packages/dwt-1.0.1_swt-3.4.1/dwt/org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/widgets/Text.d:1163

**Comment by trikko** [comment]
> Thanks for pushing me to investigate further. I couldn't find the long in the docs. Glib does indeed not force any size. However what I think is happening here is this:
> A pointer to a char is passed as an int to g_signal_emit_by_name1(). An int in D is 32bit, but a pointer on a 64 bit system (my system) is 64bit. So information is lost and a crash happens randomly in strlen (in libc).

So it should be a size_t

**Comment by jacob-carlborg** [comment]
> A pointer to a char is passed as an int to g_signal_emit_by_name1(). An int in D is 32bit, but a pointer on a 64 bit system (my system) is 64bit. So information is lost and a crash happens randomly in strlen (in libc).

I had a look in the Java source code and the parameters are typed as `int /*long*/`, it's SWT's way of indicating a pointer (they have some tool that will replace swap `int` with `long` for the 64bit version). Looking at the first parameter, `instance`, in DWT it's typed as `void*`, in SWT it's `int /*long*/`. But the last parameters are type as `int` in DWT and `int /*long*/` in SWT, not sure why they're not `void*` as well in DWT. I think the correct answer is to type them as `void*`.

**Comment by jaapgeurts** [comment]
That is probably correct in the case for the "commit" signal. The signature from the doc for commit is this:
```
void user_function (GtkIMContext *context, gchar *str, gpointer user_data)
```
So the *str is a char (char*)

When i look at the glib code. It decodes the va_args somewhere in g_signal_emit_valist() and decides to strdup() the value pointed to by a gpointer (void*). I don't have the time now to understand how  g_signal_emit_valist() works, so I don't know what type it expects in which case. I think there are signals which do expect ints (like the index into a selection). I would say casting to void* is safe or casting to long ( in any case casting to something 64 bit)

**Comment by jacob-carlborg** [comment]
BTW, do you have a small example that will reproduce this issue?

**Comment by jaapgeurts** [comment]
Here's an example. It's the example from the README.md with an added textbox. When it runs, just enter some text in the textbox until it core dumps.

[text-crash-example.zip](https://github.com/d-widget-toolkit/dwt/files/2519881/text-crash-example.zip)

**Comment by jacob-carlborg** [comment]
Fixed in 2a2a28b6acf64ac3815d78eaf51904db269b2149.

**Pull request closed without merging**
