### PR TITLE
replaced keyword body to do to avoid deprecation warnings

### PR DESCRIPTION
**Pull request by nicesai**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Nothing for Linux?

**Comment by nicesai** [comment]
Honestly I have no idea about linux versions, I made these fixes as I got these errors when compiling my app on Windows. I don't have access to a linux machine, we only use windows everywhere. :(

**Comment by jacob-carlborg** [comment]
Fair enough.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Pull request merged**
