### PR TITLE
DWT dub package prep

### PR DESCRIPTION
**Pull request by jasc2v8**
I've added the build_dub_package scripts.
They will create the 'pkg' directory.

Note the 'pkg' directory should be removed in the final.
It gets created by the scripts
I pushed it so you can understand the structure

Note the pkg-examples.
I know I've duplicated the snippets, but is is easier for the user to
use this copy rather than the full org.eclipse.swt..etc folder path

I modifed the README.markdown
Please feel free to edit to suit your needs.

Next steps:

1. I need to test on Linux (Ubuntu). I'm traveling so I'll have to do
this next week.

2. I'll delete the 'pkg' folder and any changes as a result of my Ubuntu
testing and push to you for final commit.

3. Finally, you can create the dub package at code.dlang

Awesome!

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
I don't understand what's going on here at all. You've created a `pkg` directory with all the source files. A new build script `build_dub_package.d`.

**Comment by jasc2v8** [comment]
The objective is to create a DWT dub package for code.dlang.org

Reference the instructions I added in the README.markdown document,
build_dub_package.d will build the dub package and create the pkg directory
Yes, it duplicates some files, so let me explain why:

I have included the pkg directory temporarily, 
This was done so you can see what it will look like AFTER running the build_dub_package.d file.
We will remove the pkg directory before the final commit.

We cannot set the $PACKAGE_DIR to the to level dwt folder  in the dub.sdl file!
   dwt/lib,
  dwt/org.eclipse.swt.win32.win32.x86
  dwt/res

This is because DUB will auto search these folders for src import folder and FAIL due to multiple instances of files.  Example: mozilla/*.d under both the linux and windows folders will be detected by DUB and fail with conflicting imports. 

By replicating all these files under the pkg folder, and making this the $PACKAGE_DIR, then DUB will successfully build.  DUB will now only search pkg/src, pkg/views, pkg/lib for imports.

This method allows dwt to be used as a dub repository on code.dlang.org OR simply clone the dwt repository and use as you have previously documente in the README.markdown file

My recommended changes are the method to make dwt as a dub repository on code.dlang.org

Thank you for your consideration and let me know if anything is not clear.

**Comment by jacob-carlborg** [comment]
I don't see how all this would be necessary. It's possible to use configurations and/or subpackages to specify different configurations for different platforms.

**Comment by jacob-carlborg** [comment]
I just pushed this [1] on a separate branch and that will at least build the library. I haven't tested the snippets yet.

[1] https://github.com/d-widget-toolkit/dwt/blob/dub/dub.sdl

**Comment by jasc2v8** [comment]
Understood and agreed, but I don't see how the configurations it would work as a code.dlang.org dub package.

The user can specify configurations, but DUB will still have the import conflicts mentioned above.

After you get the opportunity to try the examples and snippets, perhaps you can confirm this method, or perhaps discover a better method so DWT can be used as a dub package.

Thank you for your collaboration. I understand and appreciate these changes create more work for you.

**Comment by jacob-carlborg** [comment]
> The user can specify configurations, but DUB will still have the import conflicts mentioned above.

I don't think so. The key is the `platforms` tag [1], one for Linux and one for Windows. The documentation says:

"If no configuration is specified for a package, the first one that matches the current platform is chosen" [2].

I will give a try to see what happens with the snippets.

[1] https://github.com/d-widget-toolkit/dwt/blob/dub/dub.sdl#L19
[2] The bottom of this section: http://code.dlang.org/package-format?lang=sdl#configurations

**Comment by jasc2v8** [comment]
To simulate a code.dlang.org dub package repository, you must create a local dub package as follows;

-     $ dub add-local path/dwt 0.0.0

Now the dwt/pkg/dub.sdl dependency will work in your test environment:

-     dependency "dwt" version="==0.0.0"

**Comment by jasc2v8** [comment]
To simulate a code.dlang.org dub package repository, you must create a local dub package as follows;

-     $ dub add-local path/dwt 0.0.0

Now the dwt/pkg-examples/dub.sdl dependency will work in your test environment:

-     dependency "dwt" version="==0.0.0"

You are correct about the platform tags.  There are included in the dwt/dub.sdl file that enables the dub package to work properly with this folder structure.

**Comment by jacob-carlborg** [comment]
I gave it a try and it works on Linux. I had to add `importPaths` as well, with the same value as `sourcePaths`.

**Comment by jasc2v8** [comment]
Great.  I will modify the dwt/dub.sdl and test next week;

These currently have backslashes, only for for windows;

-     importPaths "pkg\\src"
-     stringImportPaths "pkg\\views"

I will move these to the "windows" platform
Then add forward slashes to the "linux" platform:

-     importPaths "pkg/src"
-     stringImportPaths "pkg/views"

That will resolve the issue.

**Comment by jasc2v8** [comment]
After I pushed these changes, I realized you have a separate dub branch.
Wow, that is a very sophisticated dub.sdl!
It appears you have a direction you want to take DWT for a dub package.
I will hold off on any more pull requests, unless asked.
Let me know if you want me to close this out.

**Comment by jacob-carlborg** [comment]
Yeah, there's a few tweaks left. I haven't figured out how to best handle the snippets yet.

**Comment by jasc2v8** [comment]
Looks like you are all set with dwt as a dub package, closing this...

**Pull request closed without merging**
