### PR TITLE
[win32] Add RGBA.d class

### PR DESCRIPTION
**Pull request by summer-alice**
Add the `RGBA` class for Windows.  This is a copy of the Gtk version since this is in the "common" package for SWT.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
> This is a copy of the Gtk version since this is in the "common" package for SWT.

I'm wondering if it's time to restructure the repository to more closely match the SWT repository. That would remove a lot of duplication when it comes to the common/shared packages.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by summer-alice** [comment]
> I'm wondering if it's time to restructure the repository to more closely match the SWT repository. That would remove a lot of duplication when it comes to the common/shared packages.

That would be nice.  When you say "more closely match the SWT repository", do you mean just adding a separate directory (e.g. `org.eclipse.swt.common`) with the "common" classes or having the separate directories for each "package" ([ref]) where each one contains the different platform/common code?

[ref]: https://github.com/eclipse/eclipse.platform.swt/tree/R4_7_3/bundles/org.eclipse.swt

**Comment by jacob-carlborg** [comment]
I don't know, I haven't thought of the details yet. I know that the current layout of the DWT repository is based on the pre-built SWT archives. The SWT repository has a bit different structure.

**Pull request merged**
