### PR TITLE
remove-submodules-add-inline

### PR DESCRIPTION
**Pull request by jasc2v8**
once you approve, I can add the rest.
thank you.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Hmm, GitHub claims there's a conflict. I can do the change for the submodules and then let you do the rest.

I was planning to keep the existing directory structure as is.

**Comment by jacob-carlborg** [comment]
I've inlined the submodues now. I kept the existing directory structure as is.

**Comment by jasc2v8** [comment]
Thank you, much cleaner!
I understand your desire to keep the directory structure as-is.
Let me re-think how to covert to a dub package and do another pull request in a few days
I'm also at jasc2v8@yahoo.com

**Comment by jacob-carlborg** [comment]
Cool, no rush.

**Comment by jasc2v8** [comment]
Added a new pull request from a new branch.  closing this one.

**Pull request closed without merging**
